name: DevSecOps E-commerce Pipeline

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/mini-devsecops-project:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image (load to local engine)
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: ${{ env.IMAGE }}
          push: false

      # SECURITY GATE: vulnerability scan
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ env.IMAGE }}
          format: 'table'
          exit-code: '1'
          severity: 'HIGH, CRITICAL'
          ignore-unfixed: true

      - name: Push image to Docker Hub
        if: github.event_name == 'push'
        run: docker push ${{ env.IMAGE }}
